#!/bin/sh
echo Replace obsoleted keywords
for filename in *.mds
do
    # sed options:
    #        -i[SUFFIX], --in-place[=SUFFIX]
    # 
    #               edit files in place (makes backup if SUFFIX supplied)
    sed -i -e 's/LAP_P1_E-FIELD_FIX_DURATION/LAP_P1_EFIELD_FIX_DURATION /' "$filename"
    sed -i -e 's/LAP_P2_E-FIELD_FIX_DURATION/LAP_P2_EFIELD_FIX_DURATION /' "$filename"
    
    # NOTE: Empirically, it is necessary to run sed twice, once for each substitution. Unsure why.
done     
