#! /bin/bash

# Find command history files
list=`find /opt/ddsData/archivex/tlm/* -name rpc*_cmh_cmdpf.txt`

#go through them looking for bias settings and store temporarily
rm /tmp/tmp_bias.txt >/dev/null 2>&1
for i in $list
do
grep -A 4 ARPF390A $i >>/tmp/tmp_bias.txt
done

mpb /tmp/tmp_bias.txt $1
rm /tmp/tmp_bias.txt >/dev/null 2>&1
